// TASKS------------------------------------------------------
export const FETCH_TASKS = 'FETCH_TASKS'
export const FETCH_TASKS_START = 'FETCH_TASKS_START'
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL'

export const CREATE_TASK = 'CREATE_TASK'
export const CREATE_TASK_START = 'CREATE_TASK_START'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL'

export const DELETE_TASK = 'DELETE_TASK'
export const DELETE_TASK_START = 'DELETE_TASK_START'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_FAIL = 'DELETE_TASK_FAIL'

export const UPDATE_TASK = 'UPDATE_TASK'
export const UPDATE_TASK_START = 'UPDATE_TASK_START'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_FAIL = 'UPDATE_TASK_FAIL'

// COMPANIES------------------------------------------------------
export const FETCH_COMPANIES = 'FETCH_COMPANIES'
export const FETCH_COMPANIES_START = 'FETCH_COMPANIES_START'
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS'
export const FETCH_COMPANIES_FAIL = 'FETCH_COMPANIES_FAIL'

export const CREATE_COMPANY = 'CREATE_COMPANY'
export const CREATE_COMPANY_START = 'CREATE_COMPANY_START'
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS'
export const CREATE_COMPANY_FAIL = 'CREATE_COMPANY_FAIL'

export const DELETE_COMPANY = 'DELETE_COMPANY'
export const DELETE_COMPANY_START = 'DELETE_COMPANY_START'
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS'
export const DELETE_COMPANY_FAIL = 'DELETE_COMPANY_FAIL'

export const UPDATE_COMPANY = 'UPDATE_COMPANY'
export const UPDATE_COMPANY_START = 'UPDATE_COMPANY_START'
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS'
export const UPDATE_COMPANY_FAIL = 'UPDATE_COMPANY_FAIL'
