// STORE ------------------------------------------------------
export const BACKUP_DATA = 'BACKUP_DATA'


// COMPANIES------------------------------------------------------
export const FETCH_COMPANIES = 'FETCH_COMPANIES'
export const FETCH_COMPANIES_START = 'FETCH_COMPANIES_START'
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS'
export const FETCH_COMPANIES_FAIL = 'FETCH_COMPANIES_FAIL'

export const CREATE_COMPANY = 'CREATE_COMPANY'
export const CREATE_COMPANY_START = 'CREATE_COMPANY_START'
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS'
export const CREATE_COMPANY_FAIL = 'CREATE_COMPANY_FAIL'

export const DELETE_COMPANY = 'DELETE_COMPANY'
export const DELETE_COMPANY_START = 'DELETE_COMPANY_START'
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS'
export const DELETE_COMPANY_FAIL = 'DELETE_COMPANY_FAIL'

export const UPDATE_COMPANY = 'UPDATE_COMPANY'
export const UPDATE_COMPANY_START = 'UPDATE_COMPANY_START'
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS'
export const UPDATE_COMPANY_FAIL = 'UPDATE_COMPANY_FAIL'

// CONTACTS------------------------------------------------------
export const FETCH_CONTACTS = 'FETCH_CONTACTS'
export const FETCH_CONTACTS_START = 'FETCH_CONTACTS_START'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
export const FETCH_CONTACTS_FAIL = 'FETCH_CONTACTS_FAIL'

export const CREATE_CONTACT = 'CREATE_CONTACT'
export const CREATE_CONTACT_START = 'CREATE_CONTACT_START'
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS'
export const CREATE_CONTACT_FAIL = 'CREATE_CONTACT_FAIL'

export const DELETE_CONTACT = 'DELETE_CONTACT'
export const DELETE_CONTACT_START = 'DELETE_CONTACT_START'
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS'
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL'

export const UPDATE_CONTACT = 'UPDATE_CONTACT'
export const UPDATE_CONTACT_START = 'UPDATE_CONTACT_START'
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS'
export const UPDATE_CONTACT_FAIL = 'UPDATE_CONTACT_FAIL'

// JOBS------------------------------------------------------
export const FETCH_JOBS = 'FETCH_JOBS'
export const FETCH_JOBS_START = 'FETCH_JOBS_START'
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS'
export const FETCH_JOBS_FAIL = 'FETCH_JOBS_FAIL'

export const CREATE_JOB = 'CREATE_JOB'
export const CREATE_JOB_START = 'CREATE_JOB_START'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL'

export const DELETE_JOB = 'DELETE_JOB'
export const DELETE_JOB_START = 'DELETE_JOB_START'
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS'
export const DELETE_JOB_FAIL = 'DELETE_JOB_FAIL'

export const UPDATE_JOB = 'UPDATE_JOB'
export const UPDATE_JOB_START = 'UPDATE_JOB_START'
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS'
export const UPDATE_JOB_FAIL = 'UPDATE_JOB_FAIL'

// STEPS------------------------------------------------------
export const FETCH_STEPS = 'FETCH_STEPS'
export const FETCH_STEPS_START = 'FETCH_STEPS_START'
export const FETCH_STEPS_SUCCESS = 'FETCH_STEPS_SUCCESS'
export const FETCH_STEPS_FAIL = 'FETCH_STEPS_FAIL'

export const CREATE_STEP = 'CREATE_STEP'
export const CREATE_STEP_START = 'CREATE_STEP_START'
export const CREATE_STEP_SUCCESS = 'CREATE_STEP_SUCCESS'
export const CREATE_STEP_FAIL = 'CREATE_STEP_FAIL'

export const DELETE_STEP = 'DELETE_STEP'
export const DELETE_STEP_START = 'DELETE_STEP_START'
export const DELETE_STEP_SUCCESS = 'DELETE_STEP_SUCCESS'
export const DELETE_STEP_FAIL = 'DELETE_STEP_FAIL'

export const UPDATE_STEP = 'UPDATE_STEP'
export const UPDATE_STEP_START = 'UPDATE_STEP_START'
export const UPDATE_STEP_SUCCESS = 'UPDATE_STEP_SUCCESS'
export const UPDATE_STEP_FAIL = 'UPDATE_STEP_FAIL'

// TASKS------------------------------------------------------
export const FETCH_TASKS = 'FETCH_TASKS'
export const FETCH_TASKS_START = 'FETCH_TASKS_START'
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL'

export const CREATE_TASK = 'CREATE_TASK'
export const CREATE_TASK_START = 'CREATE_TASK_START'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL'

export const DELETE_TASK = 'DELETE_TASK'
export const DELETE_TASK_START = 'DELETE_TASK_START'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_FAIL = 'DELETE_TASK_FAIL'

export const UPDATE_TASK = 'UPDATE_TASK'
export const UPDATE_TASK_START = 'UPDATE_TASK_START'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_FAIL = 'UPDATE_TASK_FAIL'

// USERS------------------------------------------------------
export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'

export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_START = 'CREATE_USER_START'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_START = 'DELETE_USER_START'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_START = 'UPDATE_USER_START'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

